### PR TITLE
Added ES6 module support.

### PR DESCRIPTION
**Pull request by Mugen87**
:wave::blush:

Could this change be interesting for the project? `stats.module.js` could be used in certain `three.js` examples.

### CODE REVIEW

**Comment by mrdoob** [comment]
Oh hi!

**Comment by mrdoob** [comment]
Thanks!

**Comment by frou** [comment]
I'm not an expert on JavaScript packaging, but it seems an ESM-flavoured Stats never made it to a tagged release on NPM and hence no NPM CDNs?

Anyway, it seems like we can import it directly in the browser using a GitHub CDN:

```js
import Stats from "https://cdn.jsdelivr.net/gh/mrdoob/stats.js@master/build/stats.module.js"
```

**Comment by Methuselah96** [comment]
@mrdoob Any chance of getting a new npm version released with this change? This fixes tree-shaking for me and would love to be able to use it.

**Comment by marcofugaro** [comment]
@Methuselah96 I believe in the meantime you can import it like this

```js
import Stats from 'three/addons/libs/stats.module.js'
```

**Pull request merged**
