### PR TITLE
Converted to ES6 modules

### PR DESCRIPTION
**Pull request by terkelg**
Converted to ES6 modules and Rollup, in a way very similar to the latest ThreeJS changes ([#9310](https://github.com/mrdoob/three.js/pull/9310)).
I also updated the closure compiler and added a few NPM scripts.

### CODE REVIEW

**Comment by mrdoob** [comment]
Thanks!

**Comment by terkelg** [comment]
I'm the one thanking. I admire and appreciate all the amazing hard work you've done for the open source community.

**Comment by cfresh** [comment]
FYI This PR breaks stats.js when retreived over bower. Bower recommends you use the un-minified version as your main (which stats.js does), and the `export` at the bottom throws a syntax error in the browser.

**Comment by terkelg** [comment]
Thanks for reporting this! I haven't used it with bower before – I'll look at it

**Comment by terkelg** [comment]
I just tested this myself with bower, npm and normal script tag in the latest Chrome and didn't get any issues or syntax errors. [screenshot](http://i.imgur.com/eIIUzUN.png)

Can you post the error you got, and information about browser?

**Comment by Disorrder** [comment]
Yes, `export Stats as default` is good only for using with Webpack or smth like that, but with bower I want only concat all my libs into one file like vendor.js. That's why I have to override `"main"` to `build/stats.min.js`

**Comment by cfresh** [comment]
If you aren't seeing an error, then I am assuming you are using `build/stats.min.js`. If you use `src/Stats.js` directly in the browser you will see `Uncaught SyntaxError: Unexpected token export` on line 171. Like @Disorrder said, I am pulling down with bower and concatenating all libs into a single bundle for minification. The gulp package that takes care of bundling uses the file specified as `main` in `bower.json`, which happens to be `src/Stats.js`.

**Comment by cfresh** [comment]
Also, in case I am making it sound like the solution is to change `"main"` to `build/stats.min.js`, there was already a PR to switch it away from that (https://github.com/mrdoob/stats.js/pull/61). The reasons why you don't want to do that are listed in the PR.

**Comment by terkelg** [comment]
So what we need is to change to provide a non-minified es5 version?

**Comment by terkelg** [comment]
So what we need is to also provide a none-minified ES5 version?

**Comment by Disorrder** [comment]
@terkelg make `build/stats.js` without minify and change `"main": "build/stats.js"` into bower.json

**Comment by terkelg** [comment]
@Disorrder and @cfresh thank you so much for the feedback, I really appricate that. Can you guys test this build: https://github.com/terkelg/stats.js - If it works, I'll make a pull request

**Comment by cfresh** [comment]
The build on your fork works in my setup, thanks!

**Pull request merged**
